#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"


set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

// ### FAULT SIMULATION TO CREATE THE PATTERN DATABASE

set_context patterns -scan -design_id gate1 
set_tsdb_output_directory ../tsdb_outdir
open_tsdb ../tsdb_outdir

read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

read_cell_library ${PDK_ROOT}/tessent/memories/*.atpglib



read_design croc_soc  -design_id gate1


set_current_design croc_soc

# Specify the current mode using a different name than what was used during scan insertion with add_scan_mode command
set_current_mode lbist_sa -type internal

import_scan_mode int_mode
set_static_dft_signal_value force_testmode_i_zero 0


#must add core instance for lbist fault simulation 
add_core_instances -module *tessent_lbist

# specify the capture procedure name and the count percentage to repeat the NCP once every 256 patterns
set_lbist_controller_options -capture_procedures {ALL 78 single_pulse 10 double_pulse 10 sti_occ 2 }

set_system_mode analysis

#add_faults and simulate patterns
add_faults -all
set_random_pattern 1024
simulate_patterns -source bist -store_patterns all


write_patterns patterns/croc_soc_lbist_parallel.v -verilog -parallel -replace -parameter_list {SIM_KEEP_PATH 1}
write_tsdb -replace
exit
