#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

set_context dft -scan -design_id gate2

read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib
read_cell_library ${PDK_ROOT}/tessent/memories/*.atpglib
# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir
read_design croc_chip -design_identifier gate1 -verbose

add_black_boxes -modules { \
                    RM_IHPSG13_1P_256x64_c2_bm_bist \
             }

set_current_design croc_chip



#specify that the scan enable comes from the LBIST logic
#set source_of_scan_en_net [get_name_list [get_instances -of_modules [get_single_name [get_icl_modules *tessent_lbist -filter tessent_instrument_type==mentor::logic_bist]]]]
#set_scan_enable ${source_of_scan_en_net}/scan_en_out  unused0_i  

############################
#### Turn on more DRC for X-bounding 
set_drc_handling E09 w
set_drc_handling E11 w


# set the x-bounding options
set_xbounding_options -exclude { rst_ni }

set_system_mode analysis

# set_attribute_value [get_scan_elements -below_instances *_occ_* ] -name cluster_name -value is_occ
# create_scan_chain_family occ_chain -include_elements [get_scan_elements -filter {cluster_name == is_occ}]
# create_scan_chain_family not_occ -include_elements [get_scan_elements -filter {cluster_name != is_occ}]

# run the x-source analysis 
set_drc_handling XB1 warning
set_drc_handling XB2 warning
analyze_xbounding
report_drc_rules XB1
report_drc_rules XB2
report_xbounding 
report_xbounding -verbose -ignored_x_sources on 


#### wrapper anlaysis and insertion
##Exclude the edt_channel in and out ports from wrapper chain analysis. The ijtag_* edt_update ports are automatically excluded
#set_wrapper_chains -exclude [ get_ports {*_edt_channels_*} ]
#set_wrapper_analysis_options -exclude_ports [ get_ports {*_edt_channels_*} ]
#set_wrapper_analysis_options -exclude_ports { unused3_i unused4_o }

##Added a new wrpper dedicated cell on reset
set_dedicated_wrapper_cell_options on -ports { rst_ni }

set_wrapper_analysis_options -input_fanout_flop_threshold 100 -output_fanin_flop_threshold 40 

##Performs wrapper cell analysis
analyze_wrapper_cells
report_wrapper_cells -Verbose  





# defining an EDT scan mode and read the required scan chain configuration from the EDT config. spec
# instance of module *edt_lbist_c0
set edt_instance [get_instances -of_icl_instances [get_icl_instances -filter tessent_instrument_type==mentor::edt]]
#add_scan_mode int_mode -type internal  -edt_instances  $edt_instance -chain_count 10 
#add_scan_mode controller_chain_mode
#add_scan_mode ext_mode -type external -chain_count 2 
add_scan_mode edt_mode -edt_instance $edt_instance 
#-chain_count 10

#set_attribute_value [get_scan_elements -below_instances *_occ_* ] -name cluster_name -value is_occ
#create_scan_chain_family occ_chain -include_elements [get_scan_elements -filter {cluster_name == is_occ}]
#create_scan_chain_family not_occ -include_elements [get_scan_elements -filter {cluster_name != is_occ}]

#set edt_instance [get_name_list [get_instance -of_module [get_name [get_icl_module -filter tessent_instrument_type==mentor::edt]]]]
#add_scan_mode edt_mode  \
#              -include_chain_families {occ_chain not_occ} \
#              -single_cluster_chains on \
#              -edt_instance $edt_instance


analyze_scan_chains
report_scan_chains 
# Insert scan chains and writes the scan inserted design into tsdb_outdir directory
insert_test_logic

report_scan_chains > scan_chains.list
report_scan_cells > scan_cells.list

exit
