#! /bin/sh -f
#\
mkdir -p logfiles; mkdir -p patterns
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
proc cleanup { {pathname_list ""}  } { 
  file delete -force  simulation_outdir  ;
  file delete -force  synthesis_outdir ;
  file delete -force  patterns/* ;
  foreach pathname $pathname_list { file delete -force $pathname  ; } ;
 } 

 cleanup ;

set PDK_ROOT ../../../tech

# Specify the context to pattern -ijtag to generate LBIST pattern
set_context patterns -ijtag 

# Specify where the tsdb_outdir is to be located, default is at the current working directory
set_tsdb_output_directory ../tsdb_outdir
open_tsdb ../../croc_soc/tsdb_outdir

# Read Tessent Library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read in the scan inserted netlist/design
read_design croc_chip_top -design_id gate3 -verbose
read_design croc_soc -design_id gate1 -view full -verbose

##Read in the memory library model
read_cell_library ${PDK_ROOT}/tessent/memories/RM_IHPSG13_1P_256x64_c2_bm_bist.atpglib

set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory


set_current_design croc_chip_top 
add_input_constraints rst_ni -C1
add_input_constraints jtag_trst_ni -C1
# Report clock and dft signal settings
#set_static_dft_signal_value force_testmode_i_zero 0

add_clocks 0 clk_i -period 10ns
add_clocks 0 jtag_tck_i -period 100ns
add_clocks 0 unused2_i -period 100ns

report_static_dft_signal_settings
report_clocks

set_system_mode analysis 
set_defaults_value PatternsSpecification/SignOffOptions/simulate_instruments_in_lower_physical_instances on

#specify pattern spec settings
set patt_spec [ create_patterns_specification  ]
 report_config_data

 
process_pattern_specification
## Run Simulations
#set_simulation_library_sources -y ../../../library/memories/ -extension v -v ../../../library/standard_cells/verilog/adk.v 
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/*.v 
#run_testbench_simulations -simulator_option { -voptargs="+acc" }
run_testbench_simulations -simulator_option { -voptargs="+acc" } -compilation_options {verilog {+define+TETRAMAX +define+FUNCTIONAL}}

# If simulation fails use the command below to see which pattern failed
check_testbench_simulations -report_status

exit

