#!/bin/bash

if [ ! -f ../../tech/synopsys/ihp-sg13g2_stdcell.db ]; then
   echo "//"
   echo "//  Note: The ../library/standard_cells/synopsys/adk.db file does not exist. Running Library Compiler to create it"
   echo "//"
   lc_shell <<!
   read_lib ../../tech/ihp-sg13g2/libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_typ_1p20V_25C.lib
   write_lib sg13g2_stdcell_typ_1p20V_25C -format db -output ../../tech/synopsys/ihp-sg13g2_stdcell.db
   read_lib ../../tech/ihp-sg13g2/libs.ref/sg13g2_io/lib/sg13g2_io_typ_1p2V_3p3V_25C.lib
   write_lib sg13g2_io_typ_1p2V_3p3V_25C -format db -output ../../tech/synopsys/ihp-sg13g2_io.db
   read_lib ../../tech/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x64_c2_bm_bist_typ_1p20V_25C.lib
   write_lib RM_IHPSG13_1P_256x64_c2_bm_bist_typ_1p20V_25C -format db -output ../../tech/synopsys/RM_IHPSG13_1P_256x64_c2_bm_bist.db
   exit
!
fi

mkdir -p logfiles
dc_shell -f to_dc_synthesis.tcl | tee logfiles/run_dc_synthesis.log
