#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech
set design_name croc_chip 
# Set the context
set_context pattern -ijtag -design_id gate2

# Read the cell library 
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib
# Set the location of the TSDB. Default is the current working directory.
set_tsdb_output_directory ../tsdb_outdir

read_design ${design_name}
add_black_boxes -modules { \
                    RM_IHPSG13_1P_256x64_c2_bm_bist \
             }
set_current_design ${design_name} 

add_clocks 0 clk_i -period 100ns
add_clocks 0 ref_clk_i -period 100ns
add_clocks 0 jtag_tck_i -period 100ns
add_clocks 0 unused2_i -period 100ns
#
add_input_constraint rst_ni -C1
add_input_constraint unused0_i -C0
#set_static_dft_signal_values edt_mode 1



report_static_dft_signal_settings

check_design_rules
# Scan enable has to be tied to low


set_system_mode analysis


#read_config_data ./lbist_mbist_pattern.patspec
set spec [ create_patterns_specification ]

#add_config_element -in_wrapper $spec/Patterns(LogicBist_croc_chip)/AdvancedOptions/ConstantPortSettings rst_ni -value 1
set_config_value end_pattern -in $spec/Patterns(LogicBist_croc_chip)/TestStep(serial_load)/LogicBist/CoreInstance(.) 1023

report_config_data $spec

process_pattern_specification

set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v 
# the simulation option (-voptargs="+acc") is necessary for LBIST simulation
run_testbench_simulation -simulator_options { -voptargs="+acc" +nowarnTSCALE -quiet} -wait
check_testbench_simulations -report_status 
exit
