#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

# Set the Context to retarget ATPG Patterns from lower level child cores
set_context pattern -scan_retargeting 

# Point to the TSDB directory
set_tsdb_output_directory ../tsdb_outdir

# Open all the TSDB of the child cores
open_tsdb ../../croc_soc/tsdb_outdir

# Read the tessent cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read the verilog
set_design_sources -format verilog -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/*.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/*.v 
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -interface_only -exclude_from_file_dictionary

read_design croc_chip_top -design_id gate3 -verbose
read_design croc_soc -design_id gate1 -view graybox -verbose

set_current_design croc_chip_top

# Retarget Stuck-at patterns from processor_core 
set_current_mode retarget1_croc_soc_stuck
set_static_dft_signal_values retargeting1_mode 1
add_core_instances -instances {i_croc_soc} -core croc_soc -mode edt_stuck

set_system_mode analysis
report_clocks

# Write the TCD for the chip-level in the TSDB directory
write_tsdb_data -replace

# Read the patterns to be retargeted. The mode is specified with the add_core_instances command.
read_patterns -module croc_soc -fault_type stuck 

set_external_capture_options -pll_cycles 5 [lindex [get_timeplate_list] 0]

# Write Verilog patterns for simulation
write_patterns patterns/croc_soc_edt_stuck_retargeted.v -verilog -parallel -replace -begin 0 -end 7 -scan -parameter_list {SIM_KEEP_PATH 1}
write_patterns patterns/croc_soc_edt_stuck_retargeted_serial.v -verilog -serial -replace -Begin 0 -End 2 -parameter_list {SIM_KEEP_PATH 1}

# Write the STIL patterns used by the tester
write_patterns patterns/croc_soc_edt_stuck_retargeted.stil -stil -replace

exit
