#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech
set design_name croc_chip 
# Set context to perfrom scan insertion and stitching
set_context dft -scan -design_id gate

# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Define location of memory library files
#set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

# Read memory verilog model
#read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -exclude_from_file_dictionary
# Read the verilog


# Read the synthesized netlist
read_verilog ../3.synthesize_rtl/${design_name}_synthesized.vg
# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir

# Read the design files from the RTL insertion pass
# Use the -no_hdl switch to skip reading the netlist as the synthesized netlist has already been read
read_design ${design_name} -design_id rtl2 -no_hdl -verbose
add_black_boxes -modules { \
                    RM_IHPSG13_1P_256x64_c2_bm_bist \
             }

set_current_design ${design_name}

# No need to define the clocks as this was done during pre-dft-drc in Step 2 when EDT was inserted
# The EDT instance will be automatically marked as non-scan
# The segmented boundary scan chains are already connected to EDT and will also be excluded when other scan chains are stitched up

report_static_dft_signal_settings

set_system_mode analysis
report_scan_segments
report_clocks
report_dft_signals

# Create a scan chain family to keep all the OCC sub-chains in one single chain
set_attribute_value [get_scan_elements -below_instances *_occ_* ] -name cluster_name -value is_occ
create_scan_chain_family occ_chain -include_elements [get_scan_elements -filter {cluster_name == is_occ}]
create_scan_chain_family not_occ -include_elements [get_scan_elements -filter {cluster_name != is_occ}]

# Create a scan mode and specify EDT instance to connect the scan chains to
set edt_instance [get_name_list [get_instance -of_module [get_name [get_icl_module -filter tessent_instrument_type==mentor::edt]]]]
add_scan_mode edt_mode  \
              -include_chain_families {occ_chain not_occ} \
              -single_cluster_chains on \
              -edt_instance $edt_instance

# Analyze the scan chains and review the different scan modes and chains
analyze_scan_chains
report_scan_chains

# Insert scan chains
insert_test_logic

report_scan_chains
report_scan_cells > scan_cells.list

exit


