#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
proc cleanup { {pathname_list ""}  } { 
  file delete -force  simulation_outdir  ;
  file delete -force  synthesis_outdir ;
  foreach pathname $pathname_list { file delete -force $pathname  ; } ;
 } 

 cleanup ;

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir

##Setting context to dft and  we are inserting DFT into gate-level design
set_context dft -rtl -design_id rtl2


# Read Tessent Library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

##Read in the memory library model
set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

##Read in memory verilog model
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -exclude_from_file_dictionary -interface_only


# Read the design files from the RTL insertion pass
# Use the -no_hdl switch to skip reading the netlist as the synthesized netlist has already been read
read_design croc_soc -design_id rtl1 

set_current_design croc_soc

##Setting the design level as physical_block
set_design_level physical_block

set_dft_specification_requirements  -logic_test on
#add core instance sti sib which is going to use by NCP decoder to create cycle for mini occ
add_core_instances -instances [get_instances *_tessent_sib_sti_inst]


###===================================================================================================
## Needed for any logic test

add_dft_signals ltest_en -create_with_tdr
add_dft_signals scan_en edt_update test_clock -source_node { scan_enable edt_update test_clock }
add_dft_signals edt_clock shift_capture_clock -create_from_other_signals

## Needed for HTKLB TP
add_dft_signals observe_test_point_en  control_test_point_en x_bounding_en  controller_chain_mode
##

##Needed for MBIST

# DFT Signal used for Scan Tested Instruments like memorybist
add_dft_signals tck_occ_en
# DFT Signal used to bypass memories or to run multi-load ATPG for memories
add_dft_signals memory_bypass_en

# DFT signal to enable observation scan technology for capturing per shift and capture
add_dft_signals capture_per_cycle_static_en

set_dft_specification_requirement -logic_test on
add_dft_signals int_mode ext_mode int_ltest_en ext_ltest_en

add_clocks 0 ref_clk_i -period 10ns
add_clocks 0 jtag_tck_i -period 10ns 

register_static_dft_signal_names force_testmode_i_zero
add_dft_control_points testmode_i  -dft_signal_source_name force_testmode_i_zero -inverse_dft_signal_source

check_design_rules

set spec [create_dft_specification -sri_sib_list { occ edt lbist } ]


# Use report_config_syntax DftSpecification/edt|occ to see full syntax
report_config_data $spec

read_config_data -in $spec -from_string {

  OCC {
    ijtag_host_interface : Sib(occ);
    static_clock_control : both;
    }
}

set id_clk_list [list \
clk_i clk_i\
ref_clk_i ref_clk_i\
jtag_tck_i jtag_tck_i\
]
foreach {id clk} $id_clk_list {
  set occ [add_config_element OCC/Controller($id) -in $spec]
  set_config_value clock_intercept_node -in $occ $clk
}



# create wrapper for Hybrid TKLBIST and LogicBIST controller
read_config_data -in $spec -from_string {
   EDT {
     ijtag_host_interface : Sib(edt);
       Controller (c1) {
        longest_chain_range : 100, 200 ;
        scan_chain_count : 10;
        input_channel_count : 1;
        output_channel_count : 1;
        LogicBistOptions { 
          misr_input_ratio : 1 ;
          ShiftPowerOptions {
            present : on ;
            default_operation : disabled ;
            SwitchingThresholdPercentage {
              min : 25 ;
           }
         }
       }
    }
  }
}

read_config_data -in $spec -from_string {
  LogicBist {
    ijtag_host_interface : Sib(lbist);
    Controller(1%ctrl_lbist) {
      burn_in : on ;
      pre_post_shift_dead_cycles : 8 ;
      SingleChainForDiagnosis {
        Present : on ;
      }  
      ControllerChain {
         present : on; 
         clock : tck;
      }
      Connections {
	shift_clock_src:clk_i;
      }
      ShiftCycles { max :800 ; }   
      CaptureCycles { max : 7; }   
      PatternCount { max : 1024; }   
      WarmupPatternCount { max : 128; }   
    }
  
   NcpIndexDecoder{
      Ncp(ALL) {
        cycle(0): OCC(clk_i), OCC(ref_clk_i), OCC(jtag_tck_i);
      }
      Ncp(single_pulse) {
        cycle(0): OCC(clk_i), OCC(ref_clk_i), OCC(jtag_tck_i);
      }
      Ncp(double_pulse) {
        cycle(0): OCC(clk_i), OCC(ref_clk_i), OCC(jtag_tck_i);
        cycle(1): OCC(clk_i), OCC(ref_clk_i), OCC(jtag_tck_i);
      }
      Ncp(sti_occ) {
       cycle(0):  croc_soc_rtl1_tessent_sib_sti_inst ;
      }
    }

   }
}



process_dft_specification
## The icl for the entire design gets created
extract_icl 

# write script for design compilation
write_design_import_script  for_dc_synthesis.tcl -replace

# Make patterns
create_pattern_specification
process_pattern_specification
## Run Simulations
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v 


run_testbench_simulations -simulator_option +nowarnTSCALE


exit
