#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech
set design_name croc_chip 
# Set the context
set_context pattern -scan -design_id gate2

# Set the location of the TSDB. Default is the current working directory.
set_tsdb_output_directory ../tsdb_outdir
# Read the cell library 
# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

read_design ${design_name}
add_black_boxes -modules { \
                    RM_IHPSG13_1P_256x64_c2_bm_bist \
             }

set_current_design ${design_name} 

# setting the test mode to lbist whichis the default
# this mode is used for pattern retargetting
set_current_mode lbist
import_scan_mode edt_mode 

set_static_dft_signal_values int_ltest_en 1
#set_static_dft_signal_values all_test 1
#set_static_dft_signal_values tck_occ_en 1

# there are 3 types of instruments needed for this fault simulation
#    EDT for PRPG/COMPACTOR/MISR configuration and chain tracing
#    LBIST for the controls and chian tracing
#    OCC for clocks
# both the EDT and OCCs will be loaded with the imported scan mode 
# add_core_instances -instance {*_edt_lbist_c0_inst}
# add_core_instances -instance {*_tessent_occ_*_inst piccpu_rtl_tessent_sib_sti_inst} -param {static_clock_control external}
add_core_instances -module *tessent_lbist
#add_core_instances -instance ${design_name}_rtl2_tessent_lbist_inst
# define new no. of pattern per NCP window ( if other than hardware default)
set_lbist_controller_options -capture_procedure {clk_i_occ_ncp 90  ALL_occ_ncp 10 } 
#add_input_constraint test_clock -c0
#add_input_constraint unused2_i -c0
add_nofault [get_instance *tessent*]

# set DFT signals 

report_static_dft_signal_settings
add_input_constraint rst_ni -C1

set_system_mode analysis

set_random_patterns 1024
add_faults -all
simulate_patterns -source bist -store_patterns all
# write parallel pattern verilog testbench
write_patterns patterns/${design_name}_lbist_parallel.v -verilog -parallel -replace -parameter_list {SIM_KEEP_PATH 1}
 
# Save the TCD, PatternDB, flat model, and fault list to the TSDB
write_tsdb_data -replace
 exit

