#! /bin/sh -f
#\
mkdir -p logfiles
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../../tech

# Set context to perfrom scan insertion and stitching
set_context dft -scan -design_id gate3

# Specify where the tsdb_outdir is to be located, default is at the current working directory
set_tsdb_output_directory ../tsdb_outdir

# Open the TSDB of all the child cores
open_tsdb ../../croc_soc/tsdb_outdir


# Read the tessent cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read the verilog
set_design_sources -format verilog -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/*.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/*.v 
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v -interface_only -exclude_from_file_dictionary

read_design croc_chip_top -design_id gate2 -verbose
read_design croc_soc_GpioCount32 -design_id gate3 -view graybox -verbose

set_current_design croc_chip_top

# Specify the pipeline_stages added using add_dft_modal_connections as non-scan 
add_nonscan_instances *tessent_dft_modal_*

set_system_mode analysis
report_scan_segments
report_clocks

# Create a scan mode and specify EDT instance to connect the scan chains to
set edt_instance [get_name_list [get_instance -of_module [get_name [get_icl_module -of_instances croc_chip_top* -filter  tessent_instrument_type==mentor::edt]]] ]
add_scan_mode edt_mode -edt_instance $edt_instance

# Controller_chain_mode
#building a single chain for all ccm mode IP in all the cores and top level MM controller
set_attribute_value [get_instance i_croc_soc ] -name active_child_scan_mode -value controller_chain_mode

create_scan_chain_family ccm_mm_top -include_elements [get_scan_elements -of_child_scan_mode controller_chain_mode]
add_scan_mode controller_chain_mode  -include_chain_families {ccm_mm_top}  -include_elements  {controller_chain_mode/i_croc_soc/ccm_scan_out0 } -si_connections [get_single_name [get_auxiliary_pins unused4_i -direction input]] -so_connection [get_single_name [get_auxiliary_pins unused5_o -direction output] ] -si_associated_ports unused4_i -so_associated_ports unused5_o -enable_dft_signal controller_chain_mode



# Analyze the scan chains and review the different scan modes and chains
analyze_scan_chains
report_scan_chains

# Insert scan chains and write the scan inserted design into TSDB directory
insert_test_logic

report_scan_cells > scan_cells.list

exit

