#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

set_context pattern -scan

set_tsdb_output_directory ../tsdb_outdir


read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

## Reads in the scan inserted netlist/design
read_design croc_soc  -design_id gate1 -verbose

read_cell_library ${PDK_ROOT}/tessent/memories/*.atpglib
#
#not reading Icl since constraints ijtag signals automatically
set_current_design croc_soc



# dont import scan mode when  not reading design (no tcd)
import_scan_mode controller_chain_mode

set_current_mode ccm_atpg


set_system_mode analysis

add_faults [get_instance {*tessent_lbist_inst *tessent*single* *edt_lbist*}]

create_patterns -cov high


write_tsdb_data -replace
write_patterns patterns/croc_soc_ccm_stuck_parallel.v -verilog -parallel -replace -parameter_list {SIM_KEEP_PATH 1}
write_patterns patterns/croc_soc__ccm_stuck_serial.v -verilog -serial -replace -parameter_list {SIM_KEEP_PATH 1}

# In order to account the coverage of the faults testable by Internal modes (bypass on/off) 
read_faults -mode edt_stuck -fault_type stuck -merge

report_statistics -detail

read_faults -mode edt_stuck_bypass_disable -fault_type stuck -merge


report_statistics -detail
exit
