#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

# Set context to perfrom scan insertion and stitching
set_context dft -scan -design_id gate3

# Specify where the tsdb_outdir is to be located, default is at the current working directory
set_tsdb_output_directory ../tsdb_outdir

# Open the TSDB of all the child cores
open_tsdb ../../croc_soc/tsdb_outdir


# Read the tessent cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read the verilog
set_design_sources -format verilog -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/*.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/*.v 
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -interface_only -exclude_from_file_dictionary

read_design croc_chip_top -design_id gate2 -verbose
read_design croc_soc -design_id gate1 -view graybox -verbose

set_current_design croc_chip_top

# Specify the pipeline_stages added using add_dft_modal_connections as non-scan 
add_nonscan_instances *tessent_dft_modal_*

set_system_mode analysis
report_scan_segments
report_clocks

# Create a scan mode and specify EDT instance to connect the scan chains to
set edt_instance [get_name_list [get_instance -of_module [get_name [get_icl_module -of_instances croc_chip_top* -filter  tessent_instrument_type==mentor::edt]]] ]
add_scan_mode edt_mode -edt_instance $edt_instance

# Analyze the scan chains and review the different scan modes and chains
analyze_scan_chains
report_scan_chains

# Insert scan chains and write the scan inserted design into TSDB directory
insert_test_logic

report_scan_cells > scan_cells.list

exit

