#! /bin/sh -f
#\
mkdir -p logfiles
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
##==========TESTPOINT, Xbounding, Wrapper and Scan Insertion  ===================================== 

set PDK_ROOT ../../../tech
# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir

##Setting context to dft and  we are inserting DFT into gate-level design
set_context dft -test_points -scan -no_rtl -design_id gate3

##Read in the design # may use  -exclude_from_file_dictionary to exclude the netlist from tessent databse i
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read the synthesized netlist

##Read in the memory library model
set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

##Read in memory verilog model
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v -exclude_from_file_dictionary -interface_only
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v -exclude_from_file_dictionary -interface_only


# Read the design files from the RTL insertion pass
# Use the -no_hdl switch to skip reading the netlist as the synthesized netlist has already been read
read_design croc_soc_GpioCount32 -design_id gate2 

set_current_design croc_soc_GpioCount32

##Setting the design level as physical_block
set_design_level physical_block

set_static_dft_signal_value ltest_en 1
#set_static_dft_signal_value force_testmode_i_zero 1

report_static_dft_signal_settings

# specify the number of testpoint (integer or integer %)
set_test_point_analysis_options -total_number 500
#specify how many observe points will be observed by one scan cell
set_test_point_insertion_options  -observe_point_share 5

# specify both types of test points to reduce both pattern count  	# reduction and improve random pattern testability
set_test_point_type { lbist_test_coverage edt_pattern_count }

# specify capture per cycle observation for observation scan to observe per shift cycle
set_test_point_analysis_options -capture_per_cycle_observe_points off

# setting the shift length to the anticipated scan chain length of the design for OST
set_test_point_analysis_options -minimum_shift_length 80

# check design rule
set_system_mode analysis

# report clocks and dft signals
report_clocks
report_dft_signals

# analyze test points 
analyze_test_points
write_test_point_dofile croc_soc_GpioCount32_tpi.dofile -all -replace 
 

## exclude reset from Xbounding else will get XB DRC. Will be handled by wrapper insertion. Automation in 19.2
set_xbounding_options  -exclude  {rst_ni jtag_trst_ni}

## Perform X-bounding for LBIST
 analyze_xbounding
 report_xbounding -verbose > xbound_list
 report_xbounding -verbose -ignored_x_sources on > xbound_list_with_ignored_x_source 

#Exclude the edt_channel in and out ports from wrapper chain analysis. The ijtag_* edt_update ports are automatically excluded
set_wrapper_analysis_options -exclude_ports [ get_ports {*_edt_channels_*} ]

#Performs wrapper cell analysis
analyze_wrapper_cells
report_wrapper_cells -Verbose  > wrapper_cell.rpt

#set attribute value for inbuild chains for controller_chain_mode
set_attribute_value [get_instances *tessent_single_chain_mode_logic_*] -name active_child_scan_mode -value controller_chain_mode
set_attribute_value [get_instances *tessent_lbist_inst] -name active_child_scan_mode -value controller_chain_mode
set_attribute_value [get_instance -of_module *_edt_lbist_c1] -name active_child_scan_mode -value controller_chain_mode


# Specify different modes (internal and external) how the chains need to be stitched
# The type internal/external and enable_dft_signal are inferred from registered DFT Signals(int_mode and ext_mode)
# Create a scan mode and specify EDT instance to connect the scan chains to
set ccm [get_scan_elements -of_child_scan_mode controller_chain_mode]
set core [remove_from_collection [get_scan_elements]  $ccm]
#set core [remove_from_collection [get_scan_elements -class core] $ccm]
set edt_instance [get_instances -of_icl_instances [get_icl_instances -filter tessent_instrument_type==mentor::edt]]

add_scan_mode int_mode -edt $edt_instance -include_elements $core -enable_dft_signal int_mode

add_scan_mode controller_chain_mode -include_elements $ccm -chain_count 1 -enable_dft_signal controller_chain_mode -si_port_format ccm_scan_in%d -so_port_format ccm_scan_out%d

add_scan_mode ext_mode -chain_count 2

# Analyze the scan chains and review the different scan modes and chains before stitching the chains
analyze_scan_chains

# Insert scan chains and writes the scan inserted design into tsdb_outdir directory
insert_test_logic

report_scan_chains
report_scan_cells > scan_cells.list

exit
