#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech
set design_name croc_chip 

set env(SCAN_TOOL) "Tessent_Scan"

set_context patterns -scan

# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Point to the TSDB directory
set_tsdb_output_directory ../tsdb_outdir

# Read the scan inserted design from the TSDB
read_design ${design_name} -design_id gate2 -verbose

add_black_boxes -modules { \
                    RM_IHPSG13_1P_256x64_c2_bm_bist \
             }

set_current_design ${design_name}


set_current_mode edt_stuck 

import_scan_mode edt_mode 

report_static_dft_signal_settings
# Set the following DFT Signal values to use the boundary scan chain to apply/capture values that would normally use the I/O pads
set_static_dft_signal_values int_ltest_en 1
set_static_dft_signal_values output_pad_disable 1
set_static_dft_signal_values tck_occ_en 1
report_static_dft_signal_settings

set_system_mode analysis
add_processors localhost:4
create_patterns
# Store TCD, flat model, fault list and PatDB format files in the TSDB directory
write_tsdb_data -replace

# Write Verilog patterns for simulation
write_patterns patterns/croc_chip_stuck_parallel.v -verilog -parallel -replace -scan -parameter_list {SIM_KEEP_PATH 1}
set_pattern_filtering -sample_per_type 2
write_patterns patterns/croc_chip_stuck_serial.v -verilog -serial -replace -parameter_list {SIM_KEEP_PATH 1}

# Write the STIL pattern for application on a tester
write_patterns patterns/croc_chip_stuck.stil -stil -replace

exit

