#! /bin/csh -f

rm -rf work
vlib work

vlog ../../library/standard_cells/verilog/*.v 
vlog ../rtl/rds_process.v
vlog ../rtl/noncore_blocks/pll.v 
vlog ../rtl/noncore_blocks/iopad_sel.v 
vlog ../../library/memories/SYNC_1RW_8Kx16.v 
vlog ../tsdb_outdir/dft_inserted_designs/chip_top_post_layout.dft_inserted_design/chip_top.vg 
vlog ../../wrapped_cores/processor_core/tsdb_outdir/dft_inserted_designs/processor_core_post_layout.dft_inserted_design/processor_core.vg 
vlog ../../wrapped_cores/gps_baseband/tsdb_outdir/dft_inserted_designs/gps_baseband_post_layout.dft_inserted_design/gps_baseband.vg 

vlog patterns/chip_top_edt_parallel_stuck.v
vsim -c -voptargs="+acc" chip_top_chip_top_edt_parallel_stuck_v_ctl -l logfiles/verilog.log_chip_top_edt_parallel_stuck -do "if {0} {log -r /*}; run -all"

vlog patterns/chip_top_edt_serial_stuck.v
vsim -c -voptargs="+acc" chip_top_chip_top_edt_serial_stuck_v_ctl -l logfiles/verilog.log_chip_top_edt_serial_stuck -do "if {0} {log -r /*}; run -all"

vlog patterns/chip_top_edt_transition_parallel.v
vsim -c -voptargs="+acc" chip_top_chip_top_edt_transition_parallel_v_ctl -l logfiles/verilog.log_chip_top_edt_transition_parallel -do "if {0} {log -r /*}; run -all"

vlog patterns/chip_top_edt_transition_serial.v
vsim -c -voptargs="+acc" chip_top_chip_top_edt_transition_serial_v_ctl -l logfiles/verilog.log_chip_top_edt_transition_serial -do "if {0} {log -r /*}; run -all"

vlog patterns/processor_core_edt_stuck_retargeted.v 
vsim -c -voptargs="+acc" chip_top_processor_core_edt_stuck_retargeted_v_ctl -l logfiles/verilog.log_processor_core_edt_stuck_retargeted  -do "if {0} {log -r /*}; run -all"

vlog patterns/processor_core_edt_stuck_retargeted_serial.v 
vsim -c -voptargs="+acc" chip_top_processor_core_edt_stuck_retargeted_serial_v_ctl -l logfiles/verilog.log_processor_core_edt_stuck_retargeted_serial  -do "if {0} {log -r /*}; run -all"

vlog patterns/processor_core_edt_transition_retargeted.v 
vsim -c -voptargs="+acc" chip_top_processor_core_edt_transition_retargeted_v_ctl -l logfiles/verilog.log_processor_core_edt_transition_retargeted  -do "if {0} {log -r /*}; run -all"

vlog patterns/processor_core_edt_transition_retargeted_serial.v 
vsim -c -voptargs="+acc" chip_top_processor_core_edt_transition_retargeted_serial_v_ctl -l logfiles/verilog.log_processor_core_edt_transition_retargeted_serial  -do "if {0} {log -r /*}; run -all"

vlog patterns/gps_edt_stuck_retargeted.v 
vsim -c -voptargs="+acc" chip_top_gps_edt_stuck_retargeted_v_ctl -l logfiles/verilog.log_gps_baseband_edt_stuck_retargeted  -do "if {0} {log -r /*}; run -all"

vlog patterns/gps_edt_stuck_retargeted_serial.v 
vsim -c -voptargs="+acc" chip_top_gps_edt_stuck_retargeted_serial_v_ctl -l logfiles/verilog.log_gps_baseband_edt_stuck_retargeted_serial  -do "if {0} {log -r /*}; run -all"

vlog patterns/gps_edt_transition_retargeted.v 
vsim -c -voptargs="+acc" chip_top_gps_edt_transition_retargeted_v_ctl -l logfiles/verilog.log_gps_baseband_edt_transition_retargeted  -do "if {0} {log -r /*}; run -all"

vlog patterns/gps_edt_transition_retargeted_serial.v 
vsim -c -voptargs="+acc" chip_top_gps_edt_transition_retargeted_serial_v_ctl -l logfiles/verilog.log_gps_baseband_edt_transition_retargeted_serial  -do "if {0} {log -r /*}; run -all"



