#! /bin/sh -f
#\
mkdir -p logfiles
#\
mkdir -p patterns
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../tech
set design_name croc_chip 

set_context patterns -ijtag

set_tsdb_output_directory ../tsdb_outdir

# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Define location of memory library files
set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

# Read memory verilog model
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -exclude_from_file_dictionary -interface_only

# Read the post-scan inserted netlist
read_design ${design_name} -design_id gate -verbose

set_current_design ${design_name}

check_design_rules

# Create IJTAG and memory BIST simulation testbenches
create_patterns_specification
process_patterns_specification

# Point to the libraries and run simulation
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v 
run_testbench_simulations

# If simulation fails, use the command below to see which pattern failed
check_testbench_simulations

exit

