#! /bin/sh -f
#\
mkdir -p logfiles
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../tech

set_context dft -rtl -design_id rtl2
set_tsdb_output_directory ../tsdb_outdir

read_design croc_chip -design_id rtl1
# Read the cell library 
# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Define location of memory library files
set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

# Read memory verilog model
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v -exclude_from_file_dictionary -interface_only
# Read the verilog

set_current_design croc_chip



# Add the DFT signals
# For scan test MemoryBIST-related logic
# Define tck_occ_en to access mini-OCC during LogicBIST 
add_dft_signal ltest_en memory_bypass_en tck_occ_en 

add_dft_signals scan_en edt_update test_clock -source_node { unused0_i  unused1_i unused2_i }
add_dft_signal edt_clock shift_capture_clock -create_from_other_signals

#### DFT signals for HTKLB
#add_dft_signal controller_chain_mode
add_dft_signals control_test_point_en observe_test_point_en x_bounding_en mcp_bounding_en
#add_dft_signal async_set_reset_static_disable 
#add_dft_signal async_set_reset_dynamic_disable -create_from_other_signals
add_dft_signals edt_mode 
add_dft_signal int_ltest_en
add_dft_signal ext_ltest_en
add_dft_signals output_pad_disable


set_dft_specification_requirements -logic_test on 
add_core_instances -instances [get_instances *_tessent_sib_sti_inst]

# add the MBIST mini-OCC for LBIST test
#add_core_instances -instances [get_instances *_tessent_sib_sti_inst]

add_dft_control_points [get_auxiliary_pins unused3_i -enable -direction input] -dft_signal_source_name ltest_en
add_dft_control_points [get_auxiliary_pins unused4_o -enable -direction output] -dft_signal_source_name ltest_en

#add_clocks ref_clk_i -period 10ns
add_clocks jtag_tck_i -period 100ns


check_design_rules
# Create DFT Specification
# Populated later in this dofile
set spec [create_dft_specification -sri_sib_list {occ edt lbist } ]

### you can set this proprty if no library cells 
# set_config_value -in $spec use_rtl_cells on 

report_config_data $spec

# Read in the DFT specification data
# This test case reads in the DFT specification from a separate file
# This file is illustrated in the next example
read_config_data logic_instruments.dfpspec -in_wrapper $spec -replace 
report_config_data
# Generate and insert the hardware
process_dft_specification

# Extract IJAG network and create ICL file for the design
 extract_icl



# create the verification testbenchs IJTAG patterns
create_pattern_specification
process_pattern_specification

# Point to the libraries and run the simulation 
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/*.v 
## Run Simulations
run_testbench_simulations -compilation_options {verilog {+define+FUNCTIONAL}}
check_testbench_simulations -report_status

# synthesizing the design using DC 
# you can generate the synthesis script only without running synthesis using below commented command
run_synthesis -generate_script_only 
write_design_import_script  ../03.synthesis/croc_chip.dc_shell_import_script -replace
#run_synthesis -startup_file  ./.synopsys_dc.setup


exit

