#! /bin/sh -f
#\

cd 1.insert_bscan
./run_bscan_insertion
cd ../2.insert_edt_occ
./run_edt_occ_insertion
cd ../3.insert_scan
./run_scan_insertion
cd ../4.generate_atpg_patterns
./run_tk_chip_stuck
./run_tk_chip_transition
./run_sims
cd ../5.retarget_atpg_patterns
./run_retarget_mode1
./run_retarget_mode1_transition
./run_sims
