#! /bin/sh -f
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
proc cleanup { {pathname_list ""}  } { 
  file delete -force  simulation_outdir  ;
  file delete -force  synthesis_outdir ;
  file delete -force  patterns/* ;
  foreach pathname $pathname_list { file delete -force $pathname  ; } ;
 } 

 cleanup ;

set PDK_ROOT /home/jd.guerrero/Documents/Tessent/tech

# Specify the context to pattern -ijtag to generate LBIST pattern
set_context patterns -ijtag 

# Specify where the tsdb_outdir is to be located, default is at the current working directory
set_tsdb_output_directory ../tsdb_outdir

# Read Tessent Library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read in the scan inserted netlist/design
read_design croc_soc  -design_id gate1

##Read in the memory library model
read_cell_library ${PDK_ROOT}/tessent/memories/*.atpglib

set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory


set_current_design croc_soc 

# Report clock and dft signal settings
set_static_dft_signal_value force_testmode_i_zero 0
report_static_dft_signal_settings
report_clocks

set_system_mode analysis 

#specify pattern spec settings
set patt_spec [ create_patterns_specification  ]
 report_config_data

read_config_data -replace -in $patt_spec -from_string {
  AdvancedOptions {
    ConstantPortSettings {
      scan_enable : 0;
    }
  }
  Patterns(ICLNetwork) {
    ICLNetworkVerify(croc_soc) {
    }
  }
  Patterns(LogicBist_croc_soc) {
    ClockPeriods {
      clk_i :10.00ns;
      ref_clk_i :10.00ns;
      jtag_tck_i :10.00ns;
      test_clock: 100.00ns;
    }
   SimulationOptions {
        logic_bist_debug : off;
      }
   TestStep(serial_load) {
      LogicBist {
        CoreInstance(.) {
          run_mode : run_time_prog;
          mode_name : lbist_sa ;//same as set_current_mode in lbist fault simulation 
          begin_pattern : 0;
          end_pattern : 1023 ;
		      misr_compares : 1 ;
        }
      }
    }
  }
}
 
process_pattern_specification
## Run Simulations
#set_simulation_library_sources -y ../../../library/memories/ -extension v -v ../../../library/standard_cells/verilog/adk.v 
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v 
#run_testbench_simulations -simulator_option { -voptargs="+acc" }
run_testbench_simulations -simulator_option { -voptargs="+acc" } -compilation_options {verilog {+define+TETRAMAX}}

# If simulation fails use the command below to see which pattern failed
check_testbench_simulations -report_status

exit

